name: Build and Push Image

on:
  push:
    branches: [ "release" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DH_PASS }}" | docker login \
             -u "${{ secrets.DH_USER }}" --password-stdin

      - name: Build image
        run: docker build -t ${{ secrets.DH_REPO }}:${{ github.sha }} .

      - name: Tag latest
        run: docker tag \
             ${{ secrets.DH_REPO }}:${{ github.sha }} \
             ${{ secrets.DH_REPO }}:latest

      - name: Push images
        run: |
          docker push ${{ secrets.DH_REPO }}:${{ github.sha }}
          docker push ${{ secrets.DH_REPO }}:latest
